### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeCursorPosition' of undefined

### ISSUE THREAD

**Issue by sweettyploy** [Jsondb/jsondb-atom-plugin#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [jsondb-atom-plugin](https://github.com/Jsondb/jsondb-atom-plugin) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeCursorPosition' of undefined

```
At C:\Users\sawitta.du\.atom\packages\jsondb-atom-plugin\lib\jsondb-atom-plugin.js:68

TypeError: Cannot read property 'onDidChangeCursorPosition' of undefined
    at Object.setCursorListener (/packages/jsondb-atom-plugin/lib/jsondb-atom-plugin.js:68:21)
    at /packages/jsondb-atom-plugin/lib/jsondb-atom-plugin.js:37:44
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:424404)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:44396)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:446737)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:455581)
    at Pane.activateItem (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:457751)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1160295)
```

### Commands

```
     -9:43.5.0 jsondb-atom-plugin:toggle (input.hidden-input)
  7x -9:25 core:backspace (input.hidden-input)
     -8:26.8.0 command-palette:toggle (input.hidden-input)
     -4:26.1.0 core:paste (input.hidden-input)
 18x -4:21.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-json 0.6.0 
atom-json-editor 0.5.1 
atom-npm 0.3.1 
atom-select-npm-install 1.0.2 
build 0.70.0 
build-npm-apm 0.12.0 
busy-signal 2.0.1 
git-menu 3.0.6 
ide-json 0.2.1 
jsondb-atom-plugin 0.2.0 
language-powerquery 2.0.0 
local-storage 0.8.0 
npm 2.0.0 
npm-install 4.0.4 
open-in-developer-mode 0.3.0 
```

**Comment by FarooqKhan** [comment]
@sweettyploy thanks for reporting and trying out this plugin i will try to fix this one soon.
